import './styles/index.css'

export * from './components'
export type { BurgerProps } from './components/burger/JBurger.vue'
export type { FooterProps } from './components/footer/JFooter.vue'
export type { FooterColumnProps } from './components/footer/JFooterColumn.vue'
export type { NavbarProps } from './components/navbar/JNavbar.vue'
export type { NavbarLinkProps } from './components/navbar/JNavbarLink.vue'
export type { SidebarProps } from './components/sidebar/JSidebar.vue'
export type { SidebarGroupProps } from './components/sidebar/JSidebarGroup.vue'
export type { SidebarItemProps } from './components/sidebar/JSidebarItem.vue'
export type { AccordionProps } from './components/accordion/JAccordion.vue'
export type { AccordionItemProps } from './components/accordion/JAccordionItem.vue'
export type { AlertProps, AlertVariant } from './components/alert/JAlert.vue'
export type { AspectRatioProps } from './components/aspect-ratio/JAspectRatio.vue'
export type { AvatarProps, AvatarStatus } from './components/avatar/JAvatar.vue'
export type { AvatarGroupItem, AvatarGroupProps } from './components/avatar-group/JAvatarGroup.vue'
export type { BadgeProps, BadgeVariant } from './components/badge/JBadge.vue'
export type { BannerProps, BannerVariant } from './components/banner/JBanner.vue'
export type { BreadcrumbItem, BreadcrumbProps } from './components/breadcrumb/JBreadcrumb.vue'
export type { ButtonProps, ButtonSize, ButtonVariant } from './components/button/JButton.vue'
export type { CardProps } from './components/card/JCard.vue'
export type { CheckboxProps } from './components/checkbox/JCheckbox.vue'
export type { CollapsibleProps } from './components/collapsible/JCollapsible.vue'
export type { CommandGroup, CommandItem, CommandPaletteProps } from './components/command-palette/JCommandPalette.vue'
export { matchText } from './components/command-palette/search'
export type { DialogProps } from './components/dialog/JDialog.vue'
export type { DropdownMenuProps } from './components/dropdown-menu/JDropdownMenu.vue'
export type { DropdownMenuItemProps } from './components/dropdown-menu/JDropdownMenuItem.vue'
export type { DropdownMenuSubProps } from './components/dropdown-menu/JDropdownMenuSub.vue'
export type { EmptyStateProps } from './components/empty-state/JEmptyState.vue'
export type { FieldProps } from './components/field/useField'
export type { InputProps, InputSize } from './components/input/JInput.vue'
export type { KbdProps } from './components/kbd/JKbd.vue'
export type { PaginationProps } from './components/pagination/JPagination.vue'
export type { PopoverProps } from './components/popover/JPopover.vue'
export type { ProgressProps } from './components/progress/JProgress.vue'
export type { RadioValue } from './components/radio/context'
export type { RadioProps } from './components/radio/JRadio.vue'
export type { RadioGroupProps } from './components/radio/JRadioGroup.vue'
export type { RatingProps } from './components/rating/JRating.vue'
export type { SelectOption, SelectProps } from './components/select/JSelect.vue'
export type { SeparatorProps } from './components/separator/JSeparator.vue'
export type { SheetProps } from './components/sheet/JSheet.vue'
export type { SkeletonProps } from './components/skeleton/JSkeleton.vue'
export type { SliderProps } from './components/slider/JSlider.vue'
export type { SpinnerProps } from './components/spinner/JSpinner.vue'
export type { StatProps, StatTrend } from './components/stat/JStat.vue'
export type { SwitchProps } from './components/switch/JSwitch.vue'
export type { TabItem, TabsProps } from './components/tabs/JTabs.vue'
export type { TagProps, TagVariant } from './components/tag/JTag.vue'
export type { TextareaProps } from './components/textarea/JTextarea.vue'
export type { TimelineItemProps, TimelineItemStatus } from './components/timeline/JTimelineItem.vue'
export type { ToasterPosition, ToasterProps } from './components/toast/JToaster.vue'
export type { ToggleGroupType } from './components/toggle-group/context'
export type { ToggleGroupProps } from './components/toggle-group/JToggleGroup.vue'
export type { ToggleGroupItemProps } from './components/toggle-group/JToggleGroupItem.vue'
export type { TooltipProps } from './components/tooltip/JTooltip.vue'
export type { VisuallyHiddenProps } from './components/visually-hidden/JVisuallyHidden.vue'

export { useFocusTrap } from './composables/useFocusTrap'
export type { FocusTrapOptions } from './composables/useFocusTrap'
export { formatHotkey, matchesHotkey, useHotkey } from './composables/useHotkey'
export { useRecentCommands } from './composables/useRecentCommands'
export type { RecentCommandsOptions } from './composables/useRecentCommands'
export { useScrollLock } from './composables/useScrollLock'
export { toast, useToast } from './composables/useToast'
export type { Toast, ToastAction, ToastFn, ToastOptions, ToastType } from './composables/useToast'

export { JuxtUI, JuxtUI as default } from './plugin'
